### ISSUE TITLE
feature request: transcode a sheet specifing sheet order

### ISSUE THREAD

**Issue by aborruso** [pyexcel/pyexcel-cli#3]
Hi,
I would like to transcode in batch several xls files in csv. Inside them there are 3 sheets sometime with different names. For all these files I need to convert only the first sheet.

Is there a way to specify something like `--sheet-number 1`? If no, I think it's an interesting feature.

My solution was to use pyexcel (not cli), because `pyexcel.save_as` takes by default the first sheet.

Thank you

**Comment by chfw** [comment]
Yes, there is. `--sheet-index`

```
$ pyexcel transcode --help
Usage: pyexcel transcode [OPTIONS] SOURCE OUTPUT

  Trancode an excel file from one format to another.

  SOURCE: a file name or '-'. '-' tells the command to use stdin
  OUTPUT: a file name or '-'. '-' tells the command to use stdout

Options:
  --source-file-type TEXT         file type of the stdin if '-' as source
  --output-file-type TEXT         file type of the stdout if '-' is given
  --sheet-name TEXT               specify sheet name to operate on. Once
                                  specified, it will work on pyexcel Sheet.
  --sheet-index INTEGER           specify sheet index to operate on. Once
                                  specified, it will work on pyexcel Sheet.
  --name-columns-by-row INTEGER   use a row as column headers
  --name-rows-by-column INTEGER   use a column as row headers
  --csv-source-delimiter TEXT
  --csv-source-encoding TEXT
  --csv-source-lineterminator TEXT
  --csv-source-quotechar TEXT
  --csv-source-escapechar TEXT
  --csv-source-quoting TEXT
  --csv-source-no-doublequote
  --csv-output-delimiter TEXT
  --csv-output-encoding TEXT
  --csv-output-lineterminator TEXT
  --csv-output-quotechar TEXT
  --csv-output-escapechar TEXT
  --csv-output-quoting TEXT
  --csv-output-no-doublequote
  --help                          Show this message and exit.
```

But please be aware that, this cli interface is subject to change. `click` was used to implement this cli but is not flexible in this context where the number of keywords is unknown/unlimited and could increase in the future. So when I will have more time, I will rewrite it using google fire, which does not care how many keywords my cli interface will have. and If pyexcel would get an extra parameter, pyexcel-cli won't need to be updated.
